spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/Api_Proveedores
    username: root
    password: carlosmanuel

server:
  port: 8080

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.data.r2dbc: DEBUG